services:
  cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:so
    environment:
      TZ: ${TZ}
      LOG_LEVEL: info
      LOG_JSON: "false"
    deploy:
      placement:
        constraints:
          - node.role == manager
  
  shepherd:
    image: containrrr/shepherd
    environment:
      TZ: ${TZ}
      FILTER_SERVICES: ''
      RUN_ONCE_AND_EXIT: "true"
      APPRISE_SIDECAR_URL: notify:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 0 0 * * *
        - swarm.cronjob.skip-running=true
      placement:
        constraints:
          - node.role == manager

  notify:
    image: mazzolino/apprise-microservice:latest
    environment:
      NOTIFICATION_URLS: ${NOTIFICATION_URL}
      
